version: "3.9"
services:
  root:
    image: "coredns"
    ports:
      - "10000:53/udp"
    volumes:
      - ./testdata/nameserver:/nameserver/
    working_dir: /nameserver/
    command: -conf Corefile_root
    networks:
      app_net:
        ipv4_address: 172.16.238.10
  
  com:
    image: "coredns"
    ports:
      - "10001:53/udp"
    volumes:
      - ./testdata/nameserver:/nameserver/
    working_dir: /nameserver/
    command: -conf Corefile_com
    networks:
      app_net:
        ipv4_address: 172.16.238.11
  
  rhine-test:
    image: "coredns"
    ports:
      - "10002:53/udp"
    volumes:
      - ./testdata/nameserver:/nameserver/
    working_dir: /nameserver/
    command: -conf Corefile_rhine
    networks:
      app_net:
        ipv4_address: 172.16.238.12
  
  resolver:
    image: "sdns"
    ports:
      - "10003:53/udp"
    volumes:
      - ./testdata/resolver:/resolver/
    working_dir: /resolver/
    command: -config=./config.yml
    networks:
      app_net:
        ipv4_address: 172.16.238.13
    depends_on:
      - root

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
        - subnet: "2001:3984:3989::/64"