// Code generated by "stringer -type=CertificateUsage"; DO NOT EDIT.

package object

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CUTrustAnchor-2]
	_ = x[CUEndEntity-3]
	_ = x[CURhine-5]
}

const (
	_CertificateUsage_name_0 = "CUTrustAnchorCUEndEntity"
	_CertificateUsage_name_1 = "CURhine"
)

var (
	_CertificateUsage_index_0 = [...]uint8{0, 13, 24}
)

func (i CertificateUsage) String() string {
	switch {
	case 2 <= i && i <= 3:
		i -= 2
		return _CertificateUsage_name_0[_CertificateUsage_index_0[i]:_CertificateUsage_index_0[i+1]]
	case i == 5:
		return _CertificateUsage_name_1
	default:
		return "CertificateUsage(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
